# model parameters
train_ratio: 0.8
test_ratio: 0.2
n_layers: 2
dataset_dir: 'dataset/Shill Bidding Dataset.csv'

# training parameters
alpha: 0.001
batch_size: 256
lr: 0.00001
dropout: 0.5
epochs: 10000
hidden_units: 64
weight_decay: 0.0001

# log parameters
log_file: "bidding-log.txt"