# model parameters
train_ratio: 0.7
val_ratio: 0.1
test_ratio: 0.2
n_layers: 1
dataset_dir: 'dataset/SeoulBikeData.csv'

# training parameters
alpha: 0.001
batch_size: 256
lr: 0.000001
dropout: 0.7
epochs: 10000
hidden_units: 64
weight_decay: 0.0001

# log parameters
log_file: "bike-log.txt"